version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - rocketchat

  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    command: bash -c 'for i in `seq 1 30`; do node main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; $
    command: /bin/sh -c 'INSTANCE_IP=$$(hostname -i) node main.js'
    mem_limit: 1G
    volumes:
     - ./data/uploads:/app/uploads
     - /tmp:/tmp
    environment:
     - PORT=3000
     - ROOT_URL=http://localhost
     - MONGO_URL=mongodb://mongo:27017/rocketchat
     - MONGO_OPLOG_URL=mongodb://mongo:27017/local
     - VIRTUAL_HOST=yourdomain.tld
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    restart: unless-stopped
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    volumes:
      - ./data/db:/data/db
      - ./data/backups:/dump

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)      
  mongo-init-replica:
    image: mongo:4
    command: 'bash -c "for i in `seq 1 30`; do mongo mongo/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''loc$
    depends_on:
      - mongo
